FROM node:22-alpine AS builder

RUN corepack enable && corepack prepare pnpm@10.10.0 --activate
RUN apk add --no-cache protobuf openssl

WORKDIR /isnex/apps/auth-svc/
COPY apps/auth-svc/package*.json ./

WORKDIR /isnex
COPY ./pnpm-workspace.yaml ./pnpm-lock.yaml ./package.json ./
RUN pnpm install --frozen-lockfile --filter auth-svc...

WORKDIR /isnex/apps/auth-svc
COPY ./apps/auth-svc ./

RUN npx prisma generate

EXPOSE 3001
CMD ["pnpm", "run", "start:dev"]