# Builder Stage
FROM node:20-slim AS builder

WORKDIR /workspace

RUN apt-get update && apt-get install -y openssl

# Copy necessary files for building the app
COPY nx.json ./
COPY tsconfig*.json ./
COPY jest.config.ts ./
COPY jest.preset.js ./
COPY eslint*.config.mjs ./
COPY .npmrc ./
COPY pnpm*.yaml ./
COPY package*.json ./

# Copy the code for auth-svc specifically
COPY apps/auth-svc ./apps/auth-svc

# Install dependencies
ENV CI=true
RUN corepack enable && corepack prepare pnpm@10.10.0 --activate
RUN pnpm install

# Build the app (only for dev, as we want fast rebuilds)
RUN pnpx nx build auth-svc

# Expose ports
EXPOSE 3000

# Run the app in development mode (use something like `nx serve` if using it for hot-reload)
# CMD ["pnpx", "nx", "serve", "auth-svc"]
