"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class UserCreatedEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERID_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    URLTOKEN_FIELD_NUMBER: builtins.int
    userId: builtins.str
    email: builtins.str
    timestamp: builtins.int
    urlToken: builtins.str
    def __init__(
        self,
        *,
        userId: builtins.str = ...,
        email: builtins.str = ...,
        timestamp: builtins.int = ...,
        urlToken: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["email", b"email", "timestamp", b"timestamp", "urlToken", b"urlToken", "userId", b"userId"]) -> None: ...

global___UserCreatedEvent = UserCreatedEvent
