apiVersion: skaffold/v4beta3
kind: Config

profiles:
  # Profile cho dev với build trên Google Cloud Build
  - name: dev-cloud
    build:
      googleCloudBuild:
        projectId: isnex-459400
      artifacts:
        - image: asia.gcr.io/isnex-459400/mdop297/isnex-auth
          context: ./apps/auth-svc/
          docker:
            dockerfile: Dockerfile.dev
            buildArgs:
              NODE_ENV: development
              POSTGRES_USER: '{{.POSTGRES_USER}}'
              POSTGRES_PASSWORD: '{{.POSTGRES_PASSWORD}}'
              POSTGRES_HOST: '{{.POSTGRES_HOST}}'
              POSTGRES_PORT: '{{.DB_PORT}}'
              POSTGRES_DB: '{{.POSTGRES_DB}}'
          sync:
            manual:
              - src: 'src/**/*.ts' # ✅ Relative to context
                dest: . # ✅ Relative to WORKDIR
              - src: 'prisma/*.prisma' # ✅ Relative to context
                dest: . # ✅ Relative to WORKDIR
    manifests:
      rawYaml:
        - ./infras/k8s/*
        - ./infras/k8s-dev/*

  # Profile cho prod với build trên Google Cloud Build
  - name: prod
    build:
      googleCloudBuild:
        projectId: isnex-459400
      artifacts:
        - image: asia.gcr.io/isnex-459400/mdop297/isnex-auth
          context: ./apps/auth-svc/
          docker:
            dockerfile: Dockerfile
            buildArgs:
              POSTGRES_USER: '{{.POSTGRES_USER}}'
              POSTGRES_PASSWORD: '{{.POSTGRES_PASSWORD}}'
              POSTGRES_HOST: '{{.POSTGRES_HOST}}'
              POSTGRES_PORT: '{{.DB_PORT}}'
              POSTGRES_DB: '{{.POSTGRES_DB}}'
    manifests:
      rawYaml:
        - ./infras/k8s-dev/*
        - ./infras/k8s/*
