apiVersion: skaffold/v4beta3
kind: Config

build:
  artifacts:
    - image: isnex-auth # Tên image chung, sẽ được ánh xạ trong manifest
      context: .
      docker:
        buildArgs:
          POSTEQRES_USER: '{{.POSTGRES_USER}}'
          POSTGRES_PASSWORD: '{{.POSTGRES_PASSWORD}}'
          POSTGRES_HOST: '{{.POSTGRES_HOST}}'
          POSTGRES_PORT: '{{.DB_PORT}}'
          POSTGRES_DB: '{{.POSTGRES_DB}}'

manifests:
  rawYaml:
    - ./infras/k8s/*

profiles:
  # Profile cho dev với build trên Google Cloud Build
  - name: dev-cloud
    build:
      googleCloudBuild:
        projectId: isnex-459400
      artifacts:
        - image: asia.gcr.io/isnex-459400/mdop297/isnex-auth
          docker:
            dockerfile: apps/auth-svc/Dockerfile.dev
            buildArgs:
              NODE_ENV: development
          sync:
            manual:
              - src: 'apps/auth-svc/src/**/*.ts'
                dest: .
              - src: 'apps/auth-svc/prisma/*.prisma'
                dest: .
    manifests:
      rawYaml:
        - ./infras/k8s/*
        - ./infras/k8s-dev/*

  # Profile cho dev với build local
  - name: dev-local
    build:
      local:
        push: false
      artifacts:
        - image: mdop297/isnex-auth
          docker:
            dockerfile: apps/auth-svc/Dockerfile.dev
            buildArgs:
              NODE_ENV: development
          sync:
            manual:
              - src: 'apps/auth-svc/src/**/*.ts'
                dest: .
              - src: 'apps/auth-svc/prisma/*.prisma'
                dest: .
    manifests:
      rawYaml:
        - ./infras/k8s/*
        - ./infras/k8s-dev/*

  # Profile cho prod với build trên Google Cloud Build
  - name: prod-cloud
    build:
      googleCloudBuild:
        projectId: isnex-459400
      artifacts:
        - image: asia.gcr.io/isnex-459400/mdop297/isnex-auth
          docker:
            dockerfile: apps/auth-svc/Dockerfile
    manifests:
      rawYaml:
        - ./infras/k8s-dev/*
        - ./infras/k8s/*
