apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infras/k8s/*
    - ./infras/k8s-dev/*
build:
  local:
    push: false
  artifacts:
    - image: mdop297/isnex-auth
      context: .
      docker:
        dockerfile: apps/auth-svc/Dockerfile
        buildArgs:
          POSTGRES_USER: '${POSTGRES_USER}'
          POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
          POSTGRES_HOST: '${POSTGRES_HOST:}'
          POSTGRES_PORT: '${DB_PORT}'
          POSTGRES_DB: '${POSTGRES_DB}'
      sync:
        manual:
          - dest: .
            src: 'apps/auth-svc/src/**/*.ts'
