# generated by claude ai (full)
import time
import uuid
import traceback
from fastapi import Request, Response
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.types import ASGIApp
from src.core.utils.logger import get_logger

logger = get_logger("middleware")


class LoggingMiddleware(BaseHTTPMiddleware):
    """Middleware để log tất cả requests và responses"""

    # Sensitive fields cần mask
    SENSITIVE_FIELDS = {
        "password",
        "token",
        "api_key",
        "secret",
        "authorization",
        "cookie",
        "csrf",
    }

    def __init__(self, app: ASGIApp):
        super().__init__(app)

    async def dispatch(self, request: Request, call_next):
        # Generate request ID
        request_id = str(uuid.uuid4())[:8]
        start_time = time.time()

        # Log request info
        logger.info(
            f"[{request_id}] → {request.method} {request.url.path} "
            f"from {request.client.host if request.client else 'unknown'}"
        )

        try:
            # Process request
            response = await call_next(request)
            duration = time.time() - start_time

            # Log response
            log_level = "warning" if response.status_code >= 400 else "info"
            getattr(logger, log_level)(
                f"[{request_id}] ← {request.method} {request.url.path} "
                f"- Status: {response.status_code} "
                f"- Duration: {duration:.3f}s"
            )

            # Add request ID to response headers
            response.headers["X-Request-ID"] = request_id

            return response

        except Exception as e:
            duration = time.time() - start_time

            # Log error with full details
            logger.error(
                f"[{request_id}] ✗ REQUEST FAILED\n"
                f"  Method: {request.method}\n"
                f"  Path: {request.url.path}\n"
                f"  Client: {request.client.host if request.client else 'unknown'}\n"
                f"  User-Agent: {request.headers.get('user-agent', 'unknown')}\n"
                f"  Duration: {duration:.3f}s\n"
                f"  Error: {type(e).__name__}: {str(e)}\n"
                f"  Traceback:\n{traceback.format_exc()}"
            )

            # Re-raise để FastAPI xử lý
            raise


def mask_sensitive_data(data: dict) -> dict:
    """Mask sensitive fields trong dict"""
    if not isinstance(data, dict):
        return data

    masked = data.copy()
    for key in masked:
        if any(
            sensitive in key.lower() for sensitive in LoggingMiddleware.SENSITIVE_FIELDS
        ):
            masked[key] = "***MASKED***"
        elif isinstance(masked[key], dict):
            masked[key] = mask_sensitive_data(masked[key])

    return masked
