# logger.py, generated by claude ai
import logging
import sys
from pathlib import Path
from logging.handlers import RotatingFileHandler


class ColoredFormatter(logging.Formatter):
    """Formatter có màu cho terminal"""

    # ANSI color codes
    COLORS = {
        "DEBUG": "\033[36m",  # Cyan
        "INFO": "\033[32m",  # Green
        "WARNING": "\033[33m",  # Yellow
        "ERROR": "\033[31m",  # Red
        "CRITICAL": "\033[35m",  # Magenta
    }
    RESET = "\033[0m"
    BOLD = "\033[1m"

    def format(self, record):
        levelname_orig = record.levelname

        if levelname_orig in self.COLORS:
            levelname_color = (
                f"{self.COLORS[levelname_orig]}{self.BOLD}"
                f"{levelname_orig:<8}{self.RESET}"
            )
            record.levelname = levelname_color

        # Format message
        result = super().format(record)

        record.levelname = levelname_orig

        return result


def setup_logger(
    name: str = "app",
    level: str = "INFO",
    log_file: str = "logs/app.log",
    max_bytes: int = 10 * 1024 * 1024,  # 10MB
    backup_count: int = 3,
):
    """Setup logger đơn giản có màu"""

    log_path = Path(log_file)
    log_path.parent.mkdir(parents=True, exist_ok=True)

    # Tạo logger
    logger = logging.getLogger(name)
    logger.setLevel(getattr(logging, level.upper()))
    logger.handlers.clear()

    # Format cho console
    console_formatter = ColoredFormatter(
        "%(asctime)s | %(levelname)s | %(name)s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )

    # Format cho file
    file_formatter = logging.Formatter(
        "%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )

    # Console handler
    console = logging.StreamHandler(sys.stdout)
    console.setLevel(logging.DEBUG)
    console.setFormatter(console_formatter)
    logger.addHandler(console)

    # File handler
    file_handler = RotatingFileHandler(
        log_file, maxBytes=max_bytes, backupCount=backup_count, encoding="utf-8"
    )
    file_handler.setLevel(logging.DEBUG)
    file_handler.setFormatter(file_formatter)
    logger.addHandler(file_handler)

    # Error file handler
    error_file = str(log_path).replace(".log", "_error.log")
    error_handler = RotatingFileHandler(
        error_file, maxBytes=max_bytes, backupCount=backup_count, encoding="utf-8"
    )
    error_handler.setLevel(logging.ERROR)
    error_handler.setFormatter(file_formatter)
    logger.addHandler(error_handler)

    logger.propagate = False

    # Test log
    logger.info(f"Logger '{name}' initialized - Level: {level}")
    logger.debug(f"Log file: {log_file}")
    logger.debug(f"Error log file: {error_file}")

    return logger


def get_logger(name: str) -> logging.Logger:
    """Lấy logger"""
    logger = logging.getLogger(name)

    if not logger.handlers:
        setup_logger(name)

    return logger
