apiVersion: apps/v1
kind: Deployment
metadata:
  name: isnext-auth-depl
spec:
  selector:
    matchLabels:
      app: isnex-auth
  template:
    metadata:
      labels:
        app: isnex-auth
    spec:
      imagePullSecrets:
        - name: auth-secret
      # initContainers:
      #   - name: prisma-migrate
      #     image: asia.gcr.io/isnex-459400/mdop297/isnex-auth
      #     # image: mdop297/isnex-auth
      #     command: ['/bin/sh', '-c']
      #     args:
      #       - |
      #         set -e
      #         pnpx prisma migrate deploy --schema=apps/auth-svc/prisma/schema.prisma
      #     envFrom:
      #       - configMapRef:
      #           name: auth-config
      #       - secretRef:
      #           name: auth-secret
      #     env:
      #       - name: DATABASE_URL
      #         value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)
      containers:
        - name: isnex-auth-kub
          image: asia.gcr.io/isnex-459400/mdop297/isnex-auth
          # image: mdop297/isnex-auth
          imagePullPolicy: Always
          resources:
            limits:
              memory: '4G'
              cpu: '2'
            requests:
              memory: '2G'
              cpu: '1'
          envFrom:
            - configMapRef:
                name: auth-config
            - secretRef:
                name: auth-secret
          env:
            - name: DATABASE_URL
              value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)

---
apiVersion: v1
kind: Service
metadata:
  name: isnex-auth-svc
spec:
  selector:
    app: isnex-auth
  ports:
    - port: 3000
      targetPort: 3000
