openapi: 3.0.3
info:
  title: [Service Name] API
  description: API documentation for the [Service Name] service
  version: 1.0.0
  contact:
    name: [Team Name]
    email: [team@example.com]
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: http://localhost:8080
    description: Development server
paths:
  /[endpoint]:
    get:
      summary: [Short description of the endpoint]
      tags:
        - [Tag Name]
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/[SchemaName]'
components:
  schemas:
    [SchemaName]:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier
        name:
          type: string
          description: Name of the resource
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - BearerAuth: []