"""init tables

Revision ID: 05003413d73a
Revises: 
Create Date: 2025-10-26 06:27:29.436183

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05003413d73a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('TEXT', 'AREA', name='highlighttype').create(op.get_bind())
    sa.Enum('B', 'KB', 'MB', 'GB', name='file_size_unit_enum').create(op.get_bind())
    sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='status').create(op.get_bind())
    sa.Enum('PDF', 'WORD', 'EXCEL', 'POWERPOINT', 'IMAGE', name='source').create(op.get_bind())
    op.create_table('folder',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['folder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('folder_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_type', postgresql.ENUM('PDF', 'WORD', 'EXCEL', 'POWERPOINT', 'IMAGE', name='source', create_type=False), nullable=False),
    sa.Column('num_pages', sa.Integer(), nullable=False),
    sa.Column('embedding_status', postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='status', create_type=False), nullable=False),
    sa.Column('file_size', sa.DOUBLE_PRECISION(), nullable=False),
    sa.Column('file_unit', postgresql.ENUM('B', 'KB', 'MB', 'GB', name='file_size_unit_enum', create_type=False), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('highlight',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('highlight_type', postgresql.ENUM('TEXT', 'AREA', name='highlighttype', create_type=False), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('highlight')
    op.drop_table('document')
    op.drop_table('folder')
    sa.Enum('PDF', 'WORD', 'EXCEL', 'POWERPOINT', 'IMAGE', name='source').drop(op.get_bind())
    sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='status').drop(op.get_bind())
    sa.Enum('B', 'KB', 'MB', 'GB', name='file_size_unit_enum').drop(op.get_bind())
    sa.Enum('TEXT', 'AREA', name='highlighttype').drop(op.get_bind())
    # ### end Alembic commands ###
