"""update documents table

Revision ID: 43b39b58e4c4
Revises: 05003413d73a
Create Date: 2025-10-26 16:58:16.756399

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43b39b58e4c4'
down_revision: Union[str, Sequence[str], None] = '05003413d73a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('document', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('document', 'workspace_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
