"""update

Revision ID: 481887e85f00
Revises: 786279d67d04
Create Date: 2025-11-05 08:37:48.215538

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '481887e85f00'
down_revision: Union[str, Sequence[str], None] = '786279d67d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('highlight', sa.Column('comment', sa.TEXT(), nullable=True))
    op.drop_column('highlight', 'preview_content')
    op.drop_column('source', 'created_at')
    op.alter_column('workspace', 'icon',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspace', 'icon',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('source', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('highlight', sa.Column('preview_content', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('highlight', 'comment')
    # ### end Alembic commands ###
