"""create all tables

Revision ID: 4b7630f9296c
Revises:
Create Date: 2025-11-03 17:55:13.381584

"""

from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4b7630f9296c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("LIKE", "DISLIKE", name="reactiontype").create(op.get_bind())
    sa.Enum("USER", "SYSTEM", name="sendertype").create(op.get_bind())
    sa.Enum("USER", "WORKSPACE", name="prompttype").create(op.get_bind())
    sa.Enum("HIGHLIGHT", "NOTEBLOCK", "NOTE", "URL", name="typeofsource").create(
        op.get_bind()
    )
    sa.Enum("TEXT", "IMAGE", name="noteblocktype").create(op.get_bind())
    sa.Enum("PDF", "WORD", "EXCEL", "POWERPOINT", "IMAGE", name="filetype").create(
        op.get_bind()
    )
    sa.Enum("UPLOADED", "PROCESSING", "COMPLETED", "FAILED", name="status").create(
        op.get_bind()
    )
    sa.Enum("TEXT", "AREA", name="highlighttype").create(op.get_bind())
    op.create_table(
        "folder",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("deleted_at", postgresql.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["folder.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "note",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("icon", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("favorite", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("deleted_at", postgresql.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["note.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "personalcontext",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("content", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workspace",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("icon", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("active_conv", sa.UUID(), nullable=True),
        sa.Column("active_doc", sa.UUID(), nullable=True),
        sa.Column("active_note", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["active_conv"],
            ["conversation.id"],
            name="fk_workspace_active_conv",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["active_doc"],
            ["document.id"],
            name="fk_workspace_active_doc",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["active_note"],
            ["note.id"],
            name="fk_workspace_active_note",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "conversation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "document",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("folder_id", sa.Uuid(), nullable=True),
        sa.Column("workspace_id", sa.Uuid(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "UPLOADED",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                name="status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("file_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("num_pages", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(
                "PDF",
                "WORD",
                "EXCEL",
                "POWERPOINT",
                "IMAGE",
                name="filetype",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("file_size", sa.VARCHAR(length=16), nullable=False),
        sa.Column("deleted_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column(
            "extra_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["folder_id"],
            ["folder.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_url"),
    )
    op.create_table(
        "noteblock",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("note_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM("TEXT", "IMAGE", name="noteblocktype", create_type=False),
            nullable=False,
        ),
        sa.Column("props", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["note_id"],
            ["note.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["noteblock.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "prompt",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sa.TEXT(), nullable=True),
        sa.Column(
            "type",
            postgresql.ENUM("USER", "WORKSPACE", name="prompttype", create_type=False),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "documentworkspacelink",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("id", "document_id", "workspace_id"),
    )
    op.create_table(
        "highlight",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("color", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "highlight_type",
            postgresql.ENUM("TEXT", "AREA", name="highlighttype", create_type=False),
            nullable=False,
        ),
        sa.Column("preview_content", sa.TEXT(), nullable=True),
        sa.Column("text", sa.TEXT(), nullable=True),
        sa.Column("image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("position", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "message",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("conv_id", sa.Uuid(), nullable=False),
        sa.Column(
            "sender",
            postgresql.ENUM("USER", "SYSTEM", name="sendertype", create_type=False),
            nullable=False,
        ),
        sa.Column("model_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "reaction",
            postgresql.ENUM("LIKE", "DISLIKE", name="reactiontype", create_type=False),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conv_id"],
            ["conversation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "noteblocksourcelink",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("note_block_id", sa.Uuid(), nullable=False),
        sa.Column("note_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["note_block_id"],
            ["noteblock.id"],
        ),
        sa.ForeignKeyConstraint(
            ["note_id"],
            ["note.id"],
        ),
        sa.PrimaryKeyConstraint("id", "note_block_id", "note_id"),
    )
    op.create_table(
        "source",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(
                "HIGHLIGHT",
                "NOTEBLOCK",
                "NOTE",
                "URL",
                name="typeofsource",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("highlight_id", sa.Uuid(), nullable=True),
        sa.Column("note_id", sa.Uuid(), nullable=True),
        sa.Column("noteblock_id", sa.Uuid(), nullable=True),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("preview_content", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["highlight_id"],
            ["highlight.id"],
        ),
        sa.ForeignKeyConstraint(
            ["note_id"],
            ["note.id"],
        ),
        sa.ForeignKeyConstraint(
            ["noteblock_id"],
            ["noteblock.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("source")
    op.drop_table("noteblocksourcelink")
    op.drop_table("message")
    op.drop_table("highlight")
    op.drop_table("documentworkspacelink")
    op.drop_table("prompt")
    op.drop_table("noteblock")
    op.drop_table("document")
    op.drop_table("conversation")
    op.drop_table("workspace")
    op.drop_table("personalcontext")
    op.drop_table("note")
    op.drop_table("folder")
    sa.Enum("TEXT", "AREA", name="highlighttype").drop(op.get_bind())
    sa.Enum("UPLOADED", "PROCESSING", "COMPLETED", "FAILED", name="status").drop(
        op.get_bind()
    )
    sa.Enum("PDF", "WORD", "EXCEL", "POWERPOINT", "IMAGE", name="filetype").drop(
        op.get_bind()
    )
    sa.Enum("TEXT", "IMAGE", name="noteblocktype").drop(op.get_bind())
    sa.Enum("HIGHLIGHT", "NOTEBLOCK", "NOTE", "URL", name="typeofsource").drop(
        op.get_bind()
    )
    sa.Enum("USER", "WORKSPACE", name="prompttype").drop(op.get_bind())
    sa.Enum("USER", "SYSTEM", name="sendertype").drop(op.get_bind())
    sa.Enum("LIKE", "DISLIKE", name="reactiontype").drop(op.get_bind())
    # ### end Alembic commands ###
