"""ud-document

Revision ID: 556f1efa0de3
Revises: 4b7630f9296c
Create Date: 2025-11-04 04:56:29.310639

"""

from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "556f1efa0de3"
down_revision: Union[str, Sequence[str], None] = "4b7630f9296c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("document_workspace_id_fkey"), "document", type_="foreignkey"
    )
    op.drop_column("document", "workspace_id")
    op.create_foreign_key(
        "fk_workspace_active_doc",
        "workspace",
        "document",
        ["active_doc"],
        ["id"],
        use_alter=True,
    )
    op.create_foreign_key(
        "fk_workspace_active_conv",
        "workspace",
        "conversation",
        ["active_conv"],
        ["id"],
        use_alter=True,
    )
    op.create_foreign_key(
        "fk_workspace_active_note",
        "workspace",
        "note",
        ["active_note"],
        ["id"],
        use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_workspace_active_note", "workspace", type_="foreignkey")
    op.drop_constraint("fk_workspace_active_conv", "workspace", type_="foreignkey")
    op.drop_constraint("fk_workspace_active_doc", "workspace", type_="foreignkey")
    op.add_column(
        "document",
        sa.Column("workspace_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("document_workspace_id_fkey"),
        "document",
        "workspace",
        ["workspace_id"],
        ["id"],
    )
    # ### end Alembic commands ###
