"""add status column to document

Revision ID: 5cc9453ca235
Revises: 43b39b58e4c4
Create Date: 2025-11-02 15:27:19.472506

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cc9453ca235'
down_revision: Union[str, Sequence[str], None] = '43b39b58e4c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('status', postgresql.ENUM('UPLOADING', 'PROCESSING', 'COMPLETED', 'FAILED', name='status', create_type=False), nullable=False))
    op.add_column('document', sa.Column('type', postgresql.ENUM('PDF', 'WORD', 'EXCEL', 'POWERPOINT', 'IMAGE', name='source', create_type=False), nullable=False))
    op.drop_column('document', 'source_type')
    op.drop_column('document', 'workspace_id')
    op.drop_column('document', 'embedding_status')
    op.sync_enum_values(
        enum_schema='public',
        enum_name='status',
        new_values=['UPLOADING', 'PROCESSING', 'COMPLETED', 'FAILED'],
        affected_columns=[TableReference(table_schema='public', table_name='document', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='status',
        new_values=['PENDING', 'PROCESSING', 'COMPLETED', 'FAILED'],
        affected_columns=[TableReference(table_schema='public', table_name='document', column_name='status')],
        enum_values_to_rename=[],
    )
    op.add_column('document', sa.Column('embedding_status', postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='status', create_type=False), autoincrement=False, nullable=False))
    op.add_column('document', sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('document', sa.Column('source_type', postgresql.ENUM('PDF', 'WORD', 'EXCEL', 'POWERPOINT', 'IMAGE', name='source', create_type=False), autoincrement=False, nullable=False))
    op.drop_column('document', 'type')
    op.drop_column('document', 'status')
    # ### end Alembic commands ###
