"""up-noteblock-source-link

Revision ID: 786279d67d04
Revises: 556f1efa0de3
Create Date: 2025-11-04 05:09:34.310439

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '786279d67d04'
down_revision: Union[str, Sequence[str], None] = '556f1efa0de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noteblocksourcelink', sa.Column('noteblock_id', sa.Uuid(), nullable=False))
    op.add_column('noteblocksourcelink', sa.Column('source_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('noteblocksourcelink_note_id_fkey'), 'noteblocksourcelink', type_='foreignkey')
    op.drop_constraint(op.f('noteblocksourcelink_note_block_id_fkey'), 'noteblocksourcelink', type_='foreignkey')
    op.create_foreign_key(None, 'noteblocksourcelink', 'source', ['source_id'], ['id'])
    op.create_foreign_key(None, 'noteblocksourcelink', 'noteblock', ['noteblock_id'], ['id'])
    op.drop_column('noteblocksourcelink', 'note_block_id')
    op.drop_column('noteblocksourcelink', 'note_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noteblocksourcelink', sa.Column('note_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('noteblocksourcelink', sa.Column('note_block_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'noteblocksourcelink', type_='foreignkey')
    op.drop_constraint(None, 'noteblocksourcelink', type_='foreignkey')
    op.create_foreign_key(op.f('noteblocksourcelink_note_block_id_fkey'), 'noteblocksourcelink', 'noteblock', ['note_block_id'], ['id'])
    op.create_foreign_key(op.f('noteblocksourcelink_note_id_fkey'), 'noteblocksourcelink', 'note', ['note_id'], ['id'])
    op.drop_column('noteblocksourcelink', 'source_id')
    op.drop_column('noteblocksourcelink', 'noteblock_id')
    # ### end Alembic commands ###
