"""remove filesize unit

Revision ID: c22b80e30d81
Revises: 5cc9453ca235
Create Date: 2025-11-02 15:44:06.962742

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c22b80e30d81'
down_revision: Union[str, Sequence[str], None] = '5cc9453ca235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'file_unit')
    sa.Enum('B', 'KB', 'MB', 'GB', name='file_size_unit_enum').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('B', 'KB', 'MB', 'GB', name='file_size_unit_enum').create(op.get_bind())
    op.add_column('document', sa.Column('file_unit', postgresql.ENUM('B', 'KB', 'MB', 'GB', name='file_size_unit_enum', create_type=False), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
