"""add file_size to document

Revision ID: d4e254acabc9
Revises: b69554dae060
Create Date: 2025-10-26 03:37:03.339569

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4e254acabc9'
down_revision: Union[str, Sequence[str], None] = 'b69554dae060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('B', 'KB', 'MB', 'GB', name='file_size_unit_enum').create(op.get_bind())
    op.add_column('document', sa.Column('file_size', sa.DOUBLE_PRECISION(), nullable=False))
    op.add_column('document', sa.Column('file_unit', postgresql.ENUM('B', 'KB', 'MB', 'GB', name='file_size_unit_enum', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'file_unit')
    op.drop_column('document', 'file_size')
    sa.Enum('B', 'KB', 'MB', 'GB', name='file_size_unit_enum').drop(op.get_bind())
    # ### end Alembic commands ###
