"""update document

Revision ID: ebaee9a218d7
Revises: f4bf6ea870ad
Create Date: 2025-11-02 16:07:49.494541

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'ebaee9a218d7'
down_revision: Union[str, Sequence[str], None] = 'f4bf6ea870ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='status',
        new_values=['UPLOADED', 'PROCESSING', 'COMPLETED', 'FAILED'],
        affected_columns=[TableReference(table_schema='public', table_name='document', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='status',
        new_values=['UPLOADING', 'PROCESSING', 'COMPLETED', 'FAILED'],
        affected_columns=[TableReference(table_schema='public', table_name='document', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
