"""change type

Revision ID: f4bf6ea870ad
Revises: c22b80e30d81
Create Date: 2025-11-02 15:53:42.499438

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4bf6ea870ad'
down_revision: Union[str, Sequence[str], None] = 'c22b80e30d81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'file_size',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'file_size',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
