name: auth-svc

on:
  push:
    branches:
      - main
    paths:
      - 'apps/auth-svc/**'
  pull_request:

permissions:
  actions: read
  contents: read
  issues: write
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      - name: run lint, build, test
        run: |
          cd apps/auth-svc/
          pnpm run lint
          pnpm run build
          pnpm run test

  block-merge-on-failure:
    runs-on: ubuntu-latest
    needs: main # Run after main job
    if: failure() # Only run if failure.
    steps:
      - name: Add do-not-merge label
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = context.payload.pull_request?.number;
            if (prNumber) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                labels: ['do-not-merge']
              });
            }
