name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read
  issues: write # Thêm quyền để chỉnh sửa PR
  pull-requests: write # Thêm quyền để thêm label

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Connect your workspace by running "nx connect" and uncomment this line to enable task distribution
      # - run: pnpm dlx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      # Thiết lập Python và cài đặt uv
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Chọn phiên bản Python phù hợp
      - name: Install uv
        run: pip install uv

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: pnpm exec nx-cloud record -- echo Hello World
      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
      - name: Run Nx Affected Tasks
        run: pnpm exec nx affected -t lint test build
  block-merge-on-failure:
    runs-on: ubuntu-latest
    needs: main # Chạy sau job main
    if: failure() # Chỉ chạy nếu job main thất bại
    steps:
      - name: Add do-not-merge label
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = context.payload.pull_request?.number;
            if (prNumber) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                labels: ['do-not-merge']
              });
            }
